# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190112_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
