# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-12 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
